### ISSUE TITLE
`.tar.gz` bundles and web-based DAWs

### ISSUE THREAD

**Issue by geraintluff** [free-audio/web-clap#2]
When running in a web browser, the UI needs to be served from a URL where relative resources such as images can be resolved.  This isn't doesn't come automatically from a `.tar.gz` bundle.

The options I can see are:

## 1. Also serve the bundle contents via HTTP

✅ Pros:
* simple
* only downloads resources when requested

❌ Cons:
* duplicate information, more files on the site/CDN
* can't cache for offline use (no discovery mechanism)
* WASI file API is (currently) synchronous, so could block while large files are fetched

## 2. Install using [Service Worker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API)

In this model, the web-page registers a Service Worker (which can intercept HTTP requests).  It then "installs" plugins by downloading/unpacking the `.tar.gz` and serves its resources (at fictitious URLs) from a local cache.

✅ Pros:
* very offline-friendly
* all resources fetched up-front
* can still work for static sites

❌ Cons:
* complex for hosts - Service Workers can be fiddly
* might download things we don't need (e.g. audio samples we don't need yet)

## 3. DAW installs the package

The DAW's server downloads/unpacks the `.tar.gz` and serves the bundle contents from its own site.

✅ Pros:
* shared across all users
* discovery can be solved (by server-side cooperation)

❌ Cons:
* requires server-side component (can't be static site)

**Comment by geraintluff** [comment]
My favourite is option 2 (Service Workers).  It feels neat to keep things as a single `.tar.gz` download, and only unpack on the user's machine.

**Comment by abique** [comment]
If the service worker works well, then it'd be my preferred solution.
It is certainly possible to have a helper library that downloads the plugin and setup everything for the web daw?

**Comment by geraintluff** [comment]
I'll have a go at writing an example Service Worker to install the `.tar.gz`. 🙂. If that works, no need to change anything.

**Comment by geraintluff** [comment]
Yep - the Service Worker approach works. 👍  My [web-browser test host](https://signalsmith-audio.github.io/wasm-clap-browserhost/) now loads the example plugin from a `.tar.gz` bundle.

The main page thinks it's requesting `[...]/hello-clap.wclap.tar.gz/module.wasm`, but actually the Service Worker fetches `[...]/hello-clap.wclap.tar.gz` and then adds all the files to the cache with fake URLs.
